[tool.poetry]
name = "Example Project"
version = "0.0.0"
description = "Example Project"
authors = ["JafarAstro <tj294@exeter.ac.uk>"]

[tools.poetry.dependencies]
python = ">=3.8, <3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"